# Generated by Django 4.2.25 on 2025-11-04 02:59

import apps.lifecore.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lifecore', '0003_apiclienttoken_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiclienttoken',
            name='token',
            field=models.CharField(default=apps.lifecore.models.generate_token_hex, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='doctorsharelink',
            name='token',
            field=models.CharField(default=apps.lifecore.models.generate_token_hex, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(default='patient', max_length=16)),
                ('resource', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('status_code', models.IntegerField(default=200)),
                ('method', models.CharField(default='GET', max_length=8)),
                ('path', models.CharField(default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['resource', 'action'], name='lifecore_au_resourc_f2e8ed_idx'), models.Index(fields=['created_at'], name='lifecore_au_created_19dc1a_idx')],
            },
        ),
    ]
